[project]
name = "modeling-stage"
version = "1.2.0"
description = "CRISP-DM: Modeling stage"
requires-python = ">=3.9"
dependencies = ["scikit-learn", "numpy", "nltk"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
