[project]
name = "business-understanding"
version = "1.2.0"
description = "CRISP-DM: Business Understanding stage"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
