[project]
name = "deployment-stage"
version = "1.2.0"
description = "CRISP-DM: Deployment stage"
requires-python = ">=3.9"
dependencies = ["joblib"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
